# Generated by Django 4.0 on 2022-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0002_remove_purchase_amount_remove_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ord',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
