# Generated by Django 4.0 on 2022-01-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0003_purchase_ord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='ord',
        ),
    ]
