# Generated by Django 4.0 on 2022-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0005_animal_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='order',
        ),
        migrations.AddField(
            model_name='animal',
            name='order',
            field=models.ManyToManyField(to='animal_husbandary.customer'),
        ),
    ]
