# Generated by Django 4.0 on 2022-01-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0006_remove_animal_order_animal_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='purchase',
        ),
    ]
