# Generated by Django 4.0 on 2022-01-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0007_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animal_husbandary.animal'),
            preserve_default=False,
        ),
    ]
