# Generated by Django 4.0 on 2022-01-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0009_remove_vaccine_animal_vaccine_anim'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='anim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animal_husbandary.animal'),
            preserve_default=False,
        ),
    ]
