# Generated by Django 4.0 on 2022-01-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0010_food_anim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='anim',
            new_name='animalID',
        ),
    ]
