# Generated by Django 4.0 on 2022-01-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0011_rename_anim_food_animalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='qty',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
