# Generated by Django 4.0 on 2022-01-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0012_animal_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='qty',
        ),
    ]
