# Generated by Django 4.0 on 2022-01-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0016_vaccine_vaccinated_delete_vaccinated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together={('vaccineID', 'anim')},
        ),
    ]
