# Generated by Django 4.0 on 2022-02-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0018_alter_animal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='price',
            field=models.IntegerField(),
        ),
    ]
