# Generated by Django 4.0 on 2022-02-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0021_remove_animal_vaccinated_vaccine_vaccinated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='anim',
            new_name='animalID',
        ),
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together={('vaccineID', 'animalID')},
        ),
    ]
