# Generated by Django 4.0 on 2022-03-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0022_rename_anim_vaccine_animalid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sam',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_husbandary.feedback')),
            ],
        ),
    ]
