# Generated by Django 4.0 on 2022-03-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0023_sam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sam',
        ),
    ]
