# Generated by Django 4.0 on 2022-03-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_husbandary', '0024_delete_sam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eats',
        ),
    ]
